name: eazy_meals
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI and Animation
  cupertino_icons: ^1.0.8      # iOS style icons
  carousel_slider: ^5.0.0      # Image carousel
  flip_card: ^0.7.0           # Card flip animation
  lottie: ^3.3.1             # Lottie animations
  google_fonts: ^6.2.1        # Google Fonts
  flutter_bounce: ^1.1.0      # Bounce animation
  iconsax: ^0.0.8            # Iconsax icon pack
  hidden_drawer_menu: 3.0.1   # Hidden drawer navigation

  # Firebase and Authentication
  firebase_core: ^3.12.1       # Firebase core
  firebase_auth: ^5.5.1        # Firebase authentication
  google_sign_in: ^6.2.2      # Google Sign-In
  cloud_firestore: ^5.6.5     # Firestore database
  firebase_messaging: ^15.2.4 # Firebase push notifications

  # State Management and Navigation
  get: ^4.6.5                # GetX state management

  # Networking and APIs
  http: ^1.3.0              # HTTP requests
  url_launcher: ^6.3.1      # Launch URLs

  # Location and Maps
  location: ^8.0.0          # Device location
  flutter_map: ^8.1.0       # Flutter map widget
  latlong2: ^0.9.1          # Latitude/longitude utilities
  geolocator: ^13.0.2       # Geolocation services
  geocoding: ^3.0.0         # Geocoding utilities
  google_maps_flutter: ^2.5.0 # Google Maps

  # Storage and File Management
  path_provider: ^2.1.5         # File system paths
  flutter_secure_storage: ^9.2.4 # Secure storage
  shared_preferences: ^2.5.2    # Local storage

  # Media and Permissions
  image_picker: ^1.1.2         # Image selection
  permission_handler: ^11.4.0  # Permission management

  # Utilities
  fluttertoast: ^8.2.12         # Toast messages
  flutter_native_splash: ^2.4.5 # Native splash screen
  uuid: ^4.5.1                 # UUID generator
  flutter_launcher_icons: ^0.14.3 # App icon generator
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0        # Lint rules

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_crop.png"