import 'package:eazy_meals/screens/VerificationScreen.dart';
import 'package:eazy_meals/screens/splash_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:eazy_meals/screens/onboarding_screen.dart';
import 'package:eazy_meals/screens/login_screen.dart';
import 'package:eazy_meals/home/customer_dashboard.dart';
import 'package:eazy_meals/home/home_screen.dart';
import 'package:eazy_meals/home/menu_screen.dart';
import 'package:eazy_meals/home/view_all_screen.dart';
import 'package:get/get.dart';
import 'package:eazy_meals/controllers/order_status_controller.dart'; // Adjust path as needed

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize GetX controllers globally
  Get.put(OrderController()); // Register OrderController

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      // Use GetMaterialApp instead of MaterialApp for GetX
      debugShowCheckedModeBanner: false,
      home: SplashScreen(), // Use SplashScreen as the entry point
      routes: {
        '/onboarding': (context) => OnboardingScreen(),
        '/login': (context) => LoginScreen(),
        '/CustomerDashboard': (context) => CustomerDashboard(),
        '/verification': (context) => VerificationScreen(),
        '/menu': (context) => MenuScreen(),
        '/viewAll': (context) => ViewAllScreen(),
      },
    );
  }
}
