import 'package:eazy_meals/screens/home_screen.dart';
import 'package:eazy_meals/screens/login_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:eazy_meals/screens/onboarding_screen.dart';

import 'home/customer_dashboard.dart';
import 'home/home_screen.dart';
// Import your OnboardingScreen

void main() async {
  YandexMapKit.setApiKey('e8d4d239-e3e0-48f4-84db-a0cee4ed80f5');
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/onboarding', // Set OnboardingScreen as the initial route
      routes: {
        '/onboarding': (context) => OnboardingScreen(),
        '/login': (context) => LoginScreen(),
        '/CustomerDashboard': (context) => CustomerDashboard(),
      },
    );
  }
}
